name: Psalm Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Psalm Security Analysis (taint)
        run: vendor/bin/psalm --taint-analysis --output-format=sarif --report=results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif